### ISSUE TITLE
Feature Request: use XMPP instead of, or in additon to IRC protocol

### ISSUE THREAD

**Issue by soulhakr** [nlloyd/SubliminalCollaborator#32] opened 2013-06-07 22:41 UTC
XMPP is popular, widely-used protocol for communication/collaboration/etc. However, IRC usage has been diminishing of late. Any chance of implementing XMPP?

**Comment by bastiao** [comment] 2013-06-08 20:10
True. I strongly believe that it will be a good contribution if we can use Gtalk or something.

**Comment by nlloyd** [comment] 2013-06-27 19:35
Duplicate of issue #4, I have always planned to include XMPP, I only started with IRC as I felt it would be an easier way to get the basics worked out.

**Closed as completed by nlloyd** 2013-06-27 19:35 UTC
Labels: duplicate
